version: '3'

services:
 master:
  image: p7hb/docker-spark
  container_name: master
  ports:
    - "8080:8080"
    - "7077:7077"
  environment:
    - INIT_DAEMON_STEP=setup_spark
    - "constraint:node==masternode"
 w1:
  image: p7hb/docker-spark
  container_name: w1
  depends_on:
    - master
  ports:
    - "8081:8081"
  environment:
    - "SPARK_MASTER=spark://master:7077"
    - "constraint:node==wnode1"
